logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.apache.coyote.http11: debug #Http 요청정보 로그 남기기

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

    hibernate:
      ddl-auto: create

oauth:
  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    redirect_uri: http://localhost:3000/oauth/redirected/kakao
    client_secret: ${kAKAO_CLIENT_SECRET}
    scope: profile_nickname, profile_image
#  naver:
#    client_id: ${NAVER_CLIENT_ID}
#    redirect_uri: ${NAVER_REDIRECT_URI}
#    client_secret: ${NAVER_CLIENT_SECRET}
#    scope: ${NAVER_SCOPE}
  google:
    client_id: ${GOOGLE_CLIENT_ID}
    redirect_uri: http://localhost:3000/oauth/code/google
    client_secret: ${GOOGLE_CLIENT_SECRET}
    scope: email, profile